CREATE QUEUE [dbo].[InternalMailQueue]
WITH STATUS=ON,
RETENTION=OFF,
POISON_MESSAGE_HANDLING (STATUS=ON),
ACTIVATION (
STATUS=ON,
PROCEDURE_NAME=[dbo].[sp_ExternalMailQueueListener],
MAX_QUEUE_READERS=1,
EXECUTE AS N'dbo'
)
ON [PRIMARY]
GO
