CREATE QUEUE [dbo].[ExternalMailQueue]
WITH STATUS=ON,
RETENTION=OFF,
POISON_MESSAGE_HANDLING (STATUS=ON),
ACTIVATION (
STATUS=ON,
PROCEDURE_NAME=[dbo].[sp_sysmail_activate],
MAX_QUEUE_READERS=1,
EXECUTE AS N'dbo'
)
ON [PRIMARY]
GO
