CREATE TABLE [dbo].[#RG_TMP_indexes_____________________________________________________________________________________________________000000000013]
(
[Clustered] [bit] NULL,
[Xml] [bit] NULL,
[Columnstore] [bit] NULL,
[Hash] [bit] NULL,
[Spatial] [bit] NULL,
[Unique] [bit] NULL,
[Included] [bit] NULL,
[UniqueConstraint] [bit] NULL,
[Primary] [bit] NULL,
[IgnoreDupKey] [bit] NULL,
[IsPadIndex] [bit] NULL,
[IsTable] [bit] NULL,
[IsView] [bit] NULL,
[FullTextKey] [bit] NULL,
[FileGroup] [sys].[sysname] NULL,
[ParentName] [sys].[sysname] NULL,
[SchemaName] [sys].[sysname] NULL,
[IndexName] [sys].[sysname] NULL,
[FillFactor] [tinyint] NOT NULL,
[ColumnName] [sys].[sysname] NULL,
[Descending] [bit] NULL,
[Statistics] [bit] NULL,
[NoRecompute] [bit] NULL,
[IsIncremental] [bit] NULL,
[data_space_id] [int] NULL,
[dataspacetype] [char] (2) COLLATE Latin1_General_CI_AS_KS_WS NULL,
[indexid] [int] NOT NULL,
[indexcolumnid] [int] NULL,
[UsingIndex] [int] NULL,
[UsingIndexName] [sys].[sysname] NULL,
[SecondaryXmlType] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[key_ordinal] [tinyint] NULL,
[partition_ordinal] [tinyint] NULL,
[allow_row_locks] [bit] NULL,
[allow_page_locks] [bit] NULL,
[is_disabled] [bit] NULL,
[filter_definition] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[spatial_index_type] [int] NULL,
[tessellation_scheme] [nvarchar] (60) COLLATE Latin1_General_CI_AS_KS_WS NULL,
[bounding_box_xmin] [float] NULL,
[bounding_box_ymin] [float] NULL,
[bounding_box_xmax] [float] NULL,
[bounding_box_ymax] [float] NULL,
[level_1_grid] [smallint] NULL,
[level_2_grid] [smallint] NULL,
[level_3_grid] [smallint] NULL,
[level_4_grid] [smallint] NULL,
[cells_per_object] [int] NULL,
[spatial_index_id] [int] NULL,
[is_system_named] [bit] NULL,
[ObjectID] [int] NULL,
[ParentObjectId] [int] NOT NULL,
[property_list_id] [int] NULL,
[xml_index_type] [tinyint] NULL,
[primary_index_path_name] [nvarchar] (128) COLLATE Latin1_General_CI_AS NULL,
[BucketCount] [int] NULL
) ON [PRIMARY]
GO
